### ISSUE TITLE
TSP Solvers | Yuchen's Blog

### ISSUE THREAD

**Issue by CarlossShi** [CarlossShi/gitalk-comments#1]
https://www.yuchen.xyz/2022/02/06/tsp-solvers/ 

 旅行商问题求解器.

**Comment by xiaolou023** [comment]
thanks for your sharing

**Comment by xiaolou023** [comment]
我也在摸索Concorde TSP solver的使用。在windows上，你可以参考：https://qmha.wordpress.com/2016/09/14/installing-concorde-tsp-solver-on-windows-guide/。除了正文，评论也很有用。根据他的说明，我已成功尝试在windows上使用Concorde。
我写遇到了0xc000007b报错，感谢你的分享。用了cgywin 32版就ok了。

**Comment by CarlossShi** [comment]
谢谢你! 一会我去试试 😆
